### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by manuakasam** [comment]
That's no typo @samsonasik :) It's not PHP-Code it's an actual sentence :P hehe

**Comment by samsonasik** [comment]
ok, just think "our controller" is singular, not plural :)

**Comment by manuakasam** [comment]
Yes, the "controller extends a class"
But the "controller has to extend a class"
Different grammatical intention ;)

**Comment by samsonasik** [comment]
ok :+1:

**Pull request closed without merging**
